version: "3.9"

services:
    # Flask backend
    backend_local:
        build: ./backend
        container_name: backend_local
        restart: always
        environment:
            - APP_NAME=FlaskApp
        volumes:
            - './backend:/backend'
        ports:
            - "8080:8080"
        expose:
            - 8080

    # Vue.js frontend
    frontend_local:
        build: ./frontend
        container_name: frontend_local
        restart: always
        environment:
            - APP_NAME=VueApp
        ports:
            - "80:80"
